services:
  localstack:
    image: localstack/localstack:3.2
    ports:
      - "4566:4566"
    environment:
      - DEBUG=0
      - S3_ENDPOINT_STRATEGY=path
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./localstack:/var/lib/localstack
      - localstack_data:/var/lib/localstack
    env_file:
      - .env

volumes:
  localstack_data: